server:
  port: 80
  error:
    include-message: always
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DBNAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true

  flyway:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DBNAME}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    connect-retries: 10
    connect-retries-interval: 10