server:
  port: 8080
  error:
    include-message: always
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:3051/main-spart-db # Postgres DB needs to be running for this (see docker-compose.yml)
    username: admin
    password: admin
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true

  flyway:
    url: jdbc:postgresql://localhost:3051/main-spart-db
    user: admin
    password: admin
    connect-retries: 10
    connect-retries-interval: 10